.PHONY: clean All

All:
	@echo "----------Building project:[ ese_3025_2 - Debug ]----------"
	@cd "ese_3025_2" && "$(MAKE)" -f  "ese_3025_2.mk"
clean:
	@echo "----------Cleaning project:[ ese_3025_2 - Debug ]----------"
	@cd "ese_3025_2" && "$(MAKE)" -f  "ese_3025_2.mk" clean
