.PHONY: clean All

All:
	@echo "----------Building project:[ struct2 - Debug ]----------"
	@cd "struct2" && "$(MAKE)" -f  "struct2.mk"
clean:
	@echo "----------Cleaning project:[ struct2 - Debug ]----------"
	@cd "struct2" && "$(MAKE)" -f  "struct2.mk" clean
