.PHONY: clean All

All:
	@echo "----------Building project:[ main_arg - Debug ]----------"
	@cd "main_arg" && "$(MAKE)" -f  "main_arg.mk"
clean:
	@echo "----------Cleaning project:[ main_arg - Debug ]----------"
	@cd "main_arg" && "$(MAKE)" -f  "main_arg.mk" clean
