.PHONY: clean All

All:
	@echo "----------Building project:[ cnd_cmp_1 - Debug ]----------"
	@cd "cnd_cmp_1" && "$(MAKE)" -f  "cnd_cmp_1.mk"
clean:
	@echo "----------Cleaning project:[ cnd_cmp_1 - Debug ]----------"
	@cd "cnd_cmp_1" && "$(MAKE)" -f  "cnd_cmp_1.mk" clean
